# Multi-stage Next.js production image.
FROM node:22-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

FROM node:22-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_API_URL=http://localhost:8080
ARG NEXT_PUBLIC_CENTRAL_API_URL=http://app.localhost:8080/api
ARG NEXT_PUBLIC_CENTRAL_DOMAIN=app.localhost
ARG NEXT_PUBLIC_TENANT_ROOT_DOMAIN=localhost
ARG NEXT_PUBLIC_CENTRAL_API_PORT=8080
ARG NEXT_PUBLIC_TENANT_API_PORT=8080
ARG NEXT_PUBLIC_REVERB_APP_KEY=
ARG NEXT_PUBLIC_REVERB_HOST=localhost
ARG NEXT_PUBLIC_REVERB_PORT=8080
ARG NEXT_PUBLIC_REVERB_SCHEME=http

ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL \
    NEXT_PUBLIC_CENTRAL_API_URL=$NEXT_PUBLIC_CENTRAL_API_URL \
    NEXT_PUBLIC_CENTRAL_DOMAIN=$NEXT_PUBLIC_CENTRAL_DOMAIN \
    NEXT_PUBLIC_TENANT_ROOT_DOMAIN=$NEXT_PUBLIC_TENANT_ROOT_DOMAIN \
    NEXT_PUBLIC_CENTRAL_API_PORT=$NEXT_PUBLIC_CENTRAL_API_PORT \
    NEXT_PUBLIC_TENANT_API_PORT=$NEXT_PUBLIC_TENANT_API_PORT \
    NEXT_PUBLIC_REVERB_APP_KEY=$NEXT_PUBLIC_REVERB_APP_KEY \
    NEXT_PUBLIC_REVERB_HOST=$NEXT_PUBLIC_REVERB_HOST \
    NEXT_PUBLIC_REVERB_PORT=$NEXT_PUBLIC_REVERB_PORT \
    NEXT_PUBLIC_REVERB_SCHEME=$NEXT_PUBLIC_REVERB_SCHEME \
    NEXT_TELEMETRY_DISABLED=1

RUN npm run build

FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    PORT=3000 \
    HOSTNAME=0.0.0.0

RUN addgroup -S nodejs && adduser -S nextjs -G nodejs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000
CMD ["node", "server.js"]
